Function name
CEmptyCollisionListener::EndTouch(IPhysicsObject *,IPhysicsObject *,IPhysicsCollisionData *)
CEmptyCollisionListener::FluidEndTouch(IPhysicsObject *,IPhysicsFluidController *)
CEmptyCollisionListener::FluidStartTouch(IPhysicsObject *,IPhysicsFluidController *)
CEmptyCollisionListener::Friction(IPhysicsObject *,float,int,int,IPhysicsCollisionData *)
CEmptyCollisionListener::ObjectEnterTrigger(IPhysicsObject *,IPhysicsObject *)
CEmptyCollisionListener::ObjectLeaveTrigger(IPhysicsObject *,IPhysicsObject *)
CEmptyCollisionListener::StartTouch(IPhysicsObject *,IPhysicsObject *,IPhysicsCollisionData *)
CPhysicsConstraintGroup::SolvePenetration(IPhysicsObject *,IPhysicsObject *)
CPhysicsEnvironment::CreateBallsocketConstraint(IPhysicsObject *,IPhysicsObject *,IPhysicsConstraintGroup *,constraint_ballsocketparams_t const&)
CPhysicsEnvironment::CreateFixedConstraint(IPhysicsObject *,IPhysicsObject *,IPhysicsConstraintGroup *,constraint_fixedparams_t const&)
CPhysicsEnvironment::CreateFluidController(IPhysicsObject *,fluidparams_t *)
CPhysicsEnvironment::CreateHingeConstraint(IPhysicsObject *,IPhysicsObject *,IPhysicsConstraintGroup *,constraint_hingeparams_t const&)
CPhysicsEnvironment::CreateLengthConstraint(IPhysicsObject *,IPhysicsObject *,IPhysicsConstraintGroup *,constraint_lengthparams_t const&)
CPhysicsEnvironment::CreateLimitedHingeConstraint(IPhysicsObject *,IPhysicsObject *,IPhysicsConstraintGroup *,constraint_limitedhingeparams_t const&)
CPhysicsEnvironment::CreatePlayerController(IPhysicsObject *)
CPhysicsEnvironment::CreatePulleyConstraint(IPhysicsObject *,IPhysicsObject *,IPhysicsConstraintGroup *,constraint_pulleyparams_t const&)
CPhysicsEnvironment::CreateRagdollConstraint(IPhysicsObject *,IPhysicsObject *,IPhysicsConstraintGroup *,constraint_ragdollparams_t const&)
CPhysicsEnvironment::CreateShadowController(IPhysicsObject *,bool,bool)
CPhysicsEnvironment::CreateSlidingConstraint(IPhysicsObject *,IPhysicsObject *,IPhysicsConstraintGroup *,constraint_slidingparams_t const&)
CPhysicsEnvironment::CreateSpring(IPhysicsObject *,IPhysicsObject *,springparams_t *)
CPhysicsEnvironment::CreateVehicleController(IPhysicsObject *,vehicleparams_t const&,uint,IPhysicsGameTrace *)
CPhysicsEnvironment::DestroyObject(IPhysicsObject *)
CPhysicsEnvironment::FindPlayerController(IPhysicsObject *)
CPhysicsEnvironment::GetActiveObjects(IPhysicsObject **)
CPhysicsEnvironment::GetObjectSerializeSize(IPhysicsObject *)
CPhysicsEnvironment::SerializeObjectToBuffer(IPhysicsObject *,uchar *,uint)
CPhysicsEnvironment::SetObjectEventHandler(IPhysicsObjectEvent *)
CPhysicsEnvironment::TransferObject(IPhysicsObject *,IPhysicsEnvironment *)
CPhysicsInterface::DestroyObjectPairHash(IPhysicsObjectPairHash *)
CPhysicsMotionController::AttachObject(IPhysicsObject *,bool)
CPhysicsMotionController::DetachObject(IPhysicsObject *)
CPhysicsMotionController::GetObjects(IPhysicsObject **)
CPhysicsObject::GetContactPoint(Vector *,IPhysicsObject **)
CPhysics_Airboat::GetWaterDepth(Ray_t *,IPhysicsObject *)
CPlayerController::SetObject(IPhysicsObject *)
CPlayerController::Update(Vector const&,Vector const&,float,bool,IPhysicsObject *)
CShadowController::SetObject(IPhysicsObject *)
CUtlMemory<IPhysicsObject *,int>::Grow(int)
CUtlMemory<IPhysicsObject *,int>::Purge(void)   
CUtlVector<IPhysicsObject *,CUtlMemory<IPhysicsObject *,int>>::FastRemove(int)
CUtlVector<IPhysicsObject *,CUtlMemory<IPhysicsObject *,int>>::InsertBefore(int,IPhysicsObject * const&)
CUtlVector<IPhysicsObject *,CUtlMemory<IPhysicsObject *,int>>::~CUtlVector()
IPhysicsCollisionEvent::ObjectEnterTrigger(IPhysicsObject *,IPhysicsObject *)
IPhysicsCollisionEvent::ObjectLeaveTrigger(IPhysicsObject *,IPhysicsObject *)
IPhysicsObject::~IPhysicsObject()
IPhysicsObject::~IPhysicsObject()
IPhysicsObjectPairHash::~IPhysicsObjectPairHash()
IPhysicsObjectPairHash::~IPhysicsObjectPairHash()
`non-virtual thunk to'CPhysicsMotionController::AttachObject(IPhysicsObject *,bool)
`non-virtual thunk to'CPhysicsMotionController::DetachObject(IPhysicsObject *)CPhysicsMotionController::DetachObject(IPhysicsObject *)
`non-virtual thunk to'CPhysicsMotionController::GetObjects(IPhysicsObject **)
`non-virtual thunk to'CPlayerController::SetObject(IPhysicsObject *)
`non-virtual thunk to'CPlayerController::Update(Vector const&,Vector const&,float,bool,IPhysicsObject *)